USE cs411_phpfogapp_com;
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Resident Evil 5');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'UFC Undisputed 3');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Halo Reach Limited Edition');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Mortal Kombat vs. DC Universe');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'WWE 12');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Call of Duty: Modern Warfare 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Left 4 Dead 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Call of Duty: Black Ops Limited Edition w/ Bonus* Content (Xbox…');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Naruto Shippuden: Ultimate Ninja Storm Generations');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Naruto Shippuden: Ultimate Ninja Storm Generations (PS3)');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Call of Duty: World at War - Platinum Hits');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Gears of War 3');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Halo Reach');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Portal 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Saint\'s Row Limited Edition Double Pack');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', '007 Quantum Of Solace');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Battlefield 3');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Sniper: Ghost Warrior');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Call of Duty 2 Special Edition Platinum Hit');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Call of Duty: Black Ops');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Call Of Duty Black Ops');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Left 4 Dead: Game of the Year Edition');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Mortal Kombat: Komplete Edition');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Saints Row 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Command & Conquer: Red Alert 3');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Street Fighter X Tekken');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Tom Clancy\'s Rainbow Six Vegas 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Half Life 2: Orange Box');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Devil May Cry 4');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Soul Calibur IV');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Blazing Angels: Squadrons Of WWII');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Mafia II PH');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Gears of War Triple Pack');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Front Mission: Evolved');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Sniper Elite 2 w/ Preorder Bonus* Content');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Halo Wars');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Ace Combat 6: Fires or Liberation');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Kinect Hulk Hogan\'s Main Event');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Virtua Fighter 5');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Top Gun: Hard Lock');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Borderlands');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Army Of Two-The 40Th Day');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Hellboy');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Medal of Honor');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Bulletstorm');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Marvel vs Capcom 3: Fate of Two Worlds');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Halo: Combat Evolved Anniversary Edition');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Fairytale Fights');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Fallout New Vegas');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Tekken 6');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Call Of Duty 3 - Platinum Hits');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Assassin\'s Creed 2 PH');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Alan Wake');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Kinect Gunstringer');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'GoldenEye 007: Reloaded');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Soul Calibur V');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Cabela\'s North American Adventures 2011');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Supreme Commander 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Army of Two: 40th Day');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Crackdown');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Crysis 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Wet');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Call of Duty: Modern Warfare - Platinum Hits');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Eternal Sonata');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Street Fighter IV');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'WWE All Stars');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Mirror\'s Edge');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Kinect PowerUp Heroes');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Blackwater');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Crackdown 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Call of Duty: Modern Warfare 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Rogue Warrior');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Call Of Duty 4 Modern Warfare');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Shadowrun');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Naruto Shippuden: Ultimate Ninja Storm 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Mirror\'S Edge');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Soul Calibur IV');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Shadowrun');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Last Remnant');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Splinter Cell Double Agent');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', '50 Cent: Blood on the Sand');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Grand Theft Auto: Episodes From Liberty City - Pre-O…');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'EA SPORTS MMA');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Iron Man 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Dark Souls');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Terminator Salvation');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'TNA Impact');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Duke Nukem Forever');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Prince Of Persia: The Forgotten Sands');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Darksiders');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Brutal Legend');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Borderlands 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Super Street Fighter IV');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Kane & Lynch Dog Days 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Cabela\'s Survival Adventures: Shadows of Katmai');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'TimeShift');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Ultimate Marvel vs Capcom 3');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Rage');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Bayonetta');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Battlestations');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Cabela\'s Hunting Party with gun');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Hitman: Absolution');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'The Saboteur');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Dark Void');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Dead Rising - Platinum Hit');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Silent Hill: Home Coming');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Assasin\'s Creed Brotherhood');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Power Rangers Samurai for Kinect');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Steel Battalion: Heavy Armor for Kinect');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Medal of Honor: Warfighter Limited Edition');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Dead or Alive 5');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'King of Fighters XIII');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Metro: Last Light');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Majin And The Forsaken Kingdom');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Assassin\'s Creed Brotherhood');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Singularity');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Tekken Tag Tournament 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Magna Carta 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Ninja Blade');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Gears of War w/ Bonus Disk - Platinum Hits');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Rise Of The Argonauts');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', '50 Cent Blood on the Sand');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Cabela\'s Survival Adventures: Shadows of Katmai with gun (Xbox …');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Street Fighter X Tekken Special Edition');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Perfect Dark Zero - Platinum Hit');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Dragon Age Awakening');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Darkest Of Days');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Alpha Protocol: The Espionage RPG');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Jurassic: The Hunted');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Syndicate');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Red Faction: Guerilla');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Red Faction Armageddon');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Velvet Assassin');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Darkest of Days');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Golden Axe:Beast Rider');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Call Of Duty 3 Platinum');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Vanquish');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Gears of War 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Alien Vs Predator');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Deus Ex: Human Revolution');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Fable III');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Transformers Revenge Of The Fallen');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'The King of Fighters XII');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Vanquish');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Tom Clancys End War');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Sacred 2: Fallen Angel');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Lucha Libre Aaa Heroes Del Ring (XBOX 360)');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'UFC Undisputed 2010');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Lost Planet: Extreme Condition-Colonies Edition');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Warhammer: Battle March');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Damnation');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Duke Nukem Forever');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'James Cameron\'S Avatar: The Game');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Tom Clancy\'s Rainbow 6 - Patriots');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'UFC Undisputed 3 (Paperback)');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Fear 2 Project Origin');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Fighters Uncaged');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Quantum Theory');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Red Faction: Armageddon');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Aliens: Colonial Marines');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Lucha Libre Aaa: Heroes Of The Ring');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'James Bond: GoldenEye 007 Reloaded');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Sniper 2: Ghost Warrior');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Stormrise');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'XCOM');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'EA Sports MMA');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Universe At War: Earth Assault');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'UFC 2009 Undisputed');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Wet');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'X-Blades');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Dead to Rights: Retribution');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Clan of Champions');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'The Saboteur');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Thor: God Of Thunder');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Il 2: Sturmovik Birds Of Prey');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Ace Combat: Assault Horizon');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Call Of Juarez The Cartel');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Dark Messiah Of Might And Magic Elements');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Unreal Tournament 3');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Fairytale Fights');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'JASF: Jane\'s Advanced Strike Fighters');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Project Sylpheed');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Attack of the Movies 3D');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Dark Star One: Broken Alliance');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Call of Juarez: The Cartel');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Bakugan: Battle Brawlers');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Dead To Rights Retribution');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Brothers in Arms: Furious 4');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Heroes Over Europe');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Dark Void');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Kung Fu High Impact');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Enslaved: Odyssey To The West');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Prey 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Legendary');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Lost Planet 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Risen');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Nier');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Tom Clancys Rainbow Six: Vegas 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Oblivion Platinum Hits');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'The Godfather 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Cartoon Network: Punch Time Explosion');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Just Cause 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Call Of Duty-World At War');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Far Cry 3');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Syndicate (Paperback)');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Saw');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Swarm');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Brothers In Arms Hells Highway');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Earth Defense Force: Insect Armageddon');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Chronicles Of Narnia: Prince Caspian');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Mercenaries 2: World In Flames');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Borderlands');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Red Dead Redemption: Game of the Year');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Halo Reach Legendary Edition');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Halo Wars Platinum Hits');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Halo 3: ODST');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Dragon Ball Z: Ultimate Tenkaichi');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Child of Eden');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Wolfenstein');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Call of Juarez: Bound in Blood');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Splatterhouse');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Operation Flashpoint: Red River');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Fighting & Shooting', 'Fallout 3: Game of the Year');

