USE cs411_phpfogapp_com;
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Kinect Star Wars');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Resident Evil: Operation Raccoon City');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Just Cause 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Lego Pirates of the Caribbean');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Saints Row The Third');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Grand Theft Auto IV: Complete');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Devil May Cry Collection');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Lego Star Wars III: The Clone Wars');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Sonic Generations');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Sonic Free Riders');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Halo 4');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Kinect Deepak Chopra Leela');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Sims 3: Pets');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Kinect Wipeout 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Grand Theft Auto: Episodes from Liberty City');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Armored Core V');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Captain America: Super Soldier');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Sonic\'s Ultimate Genesis Collection');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Batman: Arkham Asylum - Game of the Year');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Plants Vs. Zombies (With Peggle And Zuma)');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Star Wars Force Unleashed 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Saints Row 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Kung Fu Panda 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Lego Harry Potter: Years 1-4');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Rayman: Origins');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Prototype 2 - Radnet Edition');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Fantastic Pets');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Star Wars-Force Unleashed');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Silent Hill: Downpour');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Alien vs Predator');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Assassin\'s Creed: Revelations');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Naughty Bear');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Monster Madness-Battle for Suburbia');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Assassin\'s Creed 3');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'NCIS');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Lego Indiana Jones 2: Adventure Continues');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Deus Ex Human Revolution');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Lego Harry Potter: Years 5-7');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Batman: Arkham City');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Resident Evil 5');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Spiderman-Web Of Shadows');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Star Wars: The Force Unleashed');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Dead Rising 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'How to Train Your Dragon');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Kinect Puss in Boots');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Timeshift - Pre-Owned');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Harry Potter and the Deathly Hallows Part 1');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Tron: Evolution Collector\'s Edition');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'LA Noire Complete');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Toy Story 3');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Transformers: Dark of the Moon');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Dead Space 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Cars 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Naval Assault: The Killing Tide');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Warriors Orochi 3');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Crackdown 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Rio');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Asura\'s Wrath');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Darksiders');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Soul Calibur V Collector\'s Edition');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'The Darkness II');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Homefront');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Infinite Undiscovery');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Harry Potter: Order Of The Phoenix');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Silent Hill Downpour (Paperback)');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Disney Universe');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Sonic Unleashed');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Bakugan: Defenders of the Core');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Transformers: Revenge of the Fallen');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Blood Drive');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Kinect Minute to Win It');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Max Payne 3');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Tom Clancy\'s Splinter Cell: Conviction');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'James Bond: Blood Stone');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Avatar: James Cameron - The Game');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Ninja Gaiden 3');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Xbox Live Hits Pack');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Phantom Breaker Special Edition');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Tron: Evolution');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'MySims: Sky Heroes');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Jurassic: The Hunted');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Children\'s Miracle Network 3-game Pack: Viva Pinata-Shrek-Sonic…');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Sonic Unleashed');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Ghostbusters');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Shadows of the Damned');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Dreamcast Collection');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Knights Contract');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Cars-Race O Rama');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Blades of Time');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Clash Of The Titans');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Man vs Wild');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Prince of Persia');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Brothers in Arms Hell\'s Highway');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Air Conflicts');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Cabela\'s Adventure Camp');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Transformers Revenge Of The Fallen');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Spongebob Truth Or Square');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Bolt');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Blazing Angels 2 Secret Mission');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Tornado Outbreak');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'LEGO Batman 2: DC Super Heroes');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Ben 10: Ultimate Alien');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'The Spiderwich Chronicles');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Godfather 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Bully Scholarship');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Codes & Cheats Vol.1 2012 Guide (Paperback)');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'The Golden Compass');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'The Adventures of Tintin: The Game');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Brink');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Men in Black');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Brutal Legend');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Tomb Raider');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Clash Of The Titans');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Tekken 6');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Zone of the Enders HD Collection');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Epic Mickey 2: The Power of Two');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Darksiders II Collector\'s Edition');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'BioShock 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Harry Potter: The Deathly Hallows Pt 1');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Generator Rex: Agent of Providence');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Capcom Digital Collection');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Dreamcast Collection');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Vampire Rain');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Deathsmiles Limited Edition');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Star Ocean Last Hope');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'XCOM: Enemy Unknown');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Metal Gear Solid: Revengeance');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'X-Men: Destiny');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Madagascar Escape 2 Africa');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Sleeping Dogs');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Castlevania: Lord of Shadows');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Monsters vs. Aliens');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Kane & Lynch 2: Dog Days');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Dishonored');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Dragon Age 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Resident Evil 5: Gold Edition');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Naughty Bear: Gold Edition');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Fist of the North Star: Ken\'s Rage');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Blur');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Thor: God of Thunder');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Amazing Spiderman');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Incredible Hulk');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Warhammer 40k: Space Marine');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Star Ocean: The Last Hope');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'X-Men Destiny');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Spider-Man: Edge of Time');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Battlefield: Bad Company 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'X-Men Origins: Wolverine Uncaged Edition');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Transformers: Fall of Cybertron');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Harry Potter and the Deathly Hallows Part 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Madagascar 2: Escape 2 Africa');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Rango');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Spider-Man: Edge of Time');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Sherlock Holmes vs Jack the Ripper');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Assassin\'s Creed Brotherhood Collector\'s Edition');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Bakugan Battle Brawlers');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Bayonetta');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Majin and the Forsaken Kingdom');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Tomb Raider: Underworld');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Heavy Fire Afghanistan');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'De Blob 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Lollipop Chainsaw');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Nier');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Hunted: The Demon\'s Forge (X360)');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Up');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'The Cursed Crusade');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Madagasar Escape 2 Africa');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Captain America: Super Soldier');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Super Star Kartz - Dreamworks');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Lego Harry Potter: Years 1-4');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Transformers: Revenge of the Fallen');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Otomedius Excellent');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Are You Smarter Than a 5th Grader: Game Time');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Splinter Cell Conviction: Limited Edition');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Crackdown - Platinum Hit');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Chaotic Shadow Warriors');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Sonic Generations');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Supremacy MMA');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Call of Juarez: The Cartel w/ Exclusive Optical Scope (Xbox 360…');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Saw II: Flesh & Blood');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Ace Combat: Assault Horizon');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Darksiders II w/ Preorder Bonus* 30 Day DLC');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Prince of Persia');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Bad Company 2 Platinum Hits');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Bioshock Infinite');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'You Don\'t Know Jack');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Anarchy Reigns');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Iron Man 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Battleship');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Resident Evil 6');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Inversion');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Overstrike');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Deus Ex: Human Revolution');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Deathsmiles Std Ed (XBOX 360)');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Madagascar Karts');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Guilty Gear 2: Overture');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Heroes Over Europe');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Superman Returns');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Castlevania: Lord of Shadows Collector\'s Edition');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'LA Noire w/ Walmart Exclusive\'The Slip of the Tongue\' Detective…');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Rise of Nightmares');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Max Payne 3 Signature Series Guide (Paperback)');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'South Park: The Game');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Dead Island');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Kinect Joy Ride');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Assassin\'s Creed: Brotherhood');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Transformers: War for Cybertron');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Enslaved: Odyssey to the West');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'FEAR 3');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Metal Gear Solid HD Collection');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Star Wars: Force Unleashed II Collector\'s Editon');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Binary Domain');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Oblivion Platinum Hits');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Spiderman: Shattered Dimensions');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Dead Rising 2: Off the Record');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Green Lantern: Rise of Manhunters');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Ace Combat: Assault Horizon w/ Exclusive Skill Set');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'nail\'d');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Red Dead Redemption');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Tom Clancy\'s Hawx 2');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Prototype - Platinum Hits');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Action & Adventure', 'Alice: Madness Returns');

