USE cs411_phpfogapp_com;
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Kinect Rush: Disney Pixar Adventure');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Lego Batman');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Disneyland (X360) Kinect');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Skylanders Spyro\'s Adventure Starter Pack');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Kinect Sesame Street: Once Upon a Monster');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Kinect SpongeBob Roadtrip');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Bolt');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'SpongeBob: Truth or Square');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Nicktoons MLB - Kinect compatible');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Hasbro Family Game Night Fun Pack');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'uDraw Gametablet w/ uDraw Studio: Instant Artist uDraw (X360)');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Kinectimals Now With Bears');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Sonic the Hedgehog');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Create');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Body and Brain Connection');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Spiderman Friend or Foe');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Lego Indiana Jones Origin');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Happy Feet Two');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Monsters vs. Aliens');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Sacred 2: Fallen Angel');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Cars 2: The Video Game');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Create');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Brave: The Video Game');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'uDraw Marvel Super Hero Squad: Comic Combat');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Kinect Penguins of Madagascar: Dr. Blowhole Returns Again (Xbox…');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Hasbro Family Game Night 3');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Kinect Victorious: Time to Shine');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'The Price is Right Decades');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Rabbids Alive & Kicking');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Hannah The Movie');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'National Geographic Challenge');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Madagascar 3: The Video Game');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Shrek Forever After');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Bee Movie');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Hannah Montana: The Movie');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Scene It?');
INSERT IGNORE INTO ofType (Category, Game_Title) VALUES ('Kids & Family', 'Kinectimals');

