USE cs411_phpfogapp_com;
CREATE TABLE SELLS (
  VENDOR_NAME VARCHAR(100),
  GAME_TITLE VARCHAR(10),
  GAME_CONDITION VARCHAR(5),  
  PRICE VARCHAR(7),
  FOREIGN KEY (VENDOR_NAME) REFERENCES VENDORS(NAME),
  FOREIGN KEY (GAME_TITLE) REFERENCES GAMES(TITLE),
  PRIMARY KEY (VENDOR_NAME, GAME_TITLE)
);


